### ISSUE TITLE
Integrate URL shortener service

### ISSUE THREAD

**Issue by clarencecastillo** [ntuoss/hackoss-api#4]
Since the inception of [ntuoss/tgifhacks](https://github.com/ntuoss/tgifhacks), we've been using [Rebrandly](https://www.rebrandly.com/) to handle click analytics and to make link routing easy. @HandsomeJeff has been graciously updating these links (manually) to point to the live workshop's links. We need to integrate the service to this API so it can be done automatically upon publication of an event.

**Comment by weicong96** [comment]
Refer to PR #6
